spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather_db
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  file:
    name: logs/weather.log